#define NOTHING 0
#define COLON 1
#define EQUALS 2
#define TRUE 3
#define FALSE 4
#define MULTIPLY 5
#define DIVIDE 6
#define PLUS 7
#define MINUS 8
#define IDENTIFIER 9
#define INTEGER 10
#define IF 11
#define GOES 12
#define LOOP 13
