#define NOTHING 0
#define COLON 1
#define EQUALS 2
#define TRUE 3
#define FALSE 4
#define MULTIPLY 5
#define DIVIDE 6
#define PLUS 7
#define MINUS 8
#define IDENTIFIER 9
#define INTEGER 10
#define IF 11
#define GOESS 12
#define SUM 13
#define LOOP 14
#define POT 15
#define GET 16
#define SET 17
